name: take_it_and_go
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

#depedencies for development
dependencies:
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.1.0
  lottie: ^1.3.0
  provider: ^6.0.3

# development depedencies for development
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #assets files
  assets:
    - assets/images/
    - assets/jsonFile/
  #   - images/a_dot_ham.jpeg
  # adding fonts
  # example:
  fonts:

    # appbar main title font
    - family: Dancing Script
      fonts:
        - asset: fonts/DancingScript-Bold.ttf
          weight: 900
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  # see https://flutter.dev/custom-fonts/#from-packages
